### ISSUE TITLE
Sending null 

### ISSUE THREAD

**Issue by meeshh** [icetee/palladium#4]
when i execute the command, it sends the email with null rather than the html page that I have
<img width="473" alt="screen shot 2018-03-02 at 10 29 34 pm" src="https://user-images.githubusercontent.com/620224/36920425-5339d5cc-1e69-11e8-97ef-ade6ae3719bf.png">

**Comment by icetee** [comment]
Thanks, I fixed the [v1.1.0](https://github.com/icetee/palladium/releases/tag/v1.1.0) version.
