### ISSUE TITLE
<img /> received without src=""

### ISSUE THREAD

**Issue by meeshh** [icetee/palladium#5]
images are being received in the email without the src="" attribute. so no image is being loaded in the email.

**Comment by icetee** [comment]
Unfortunately, it's hard coded to take image from the "img" folder.

But it encodes into base64 and handles CID-it.

Would you test it?

**Comment by meeshh** [comment]
so there is no way to do it without a base64 encoding? i have all my images hosted somewhere online

**Comment by icetee** [comment]
no, but I'll do it

**Comment by icetee** [comment]
Can you test the last commit? Only change the `~/.atom/packages/palladium/lib/components/mailer.js` file and reset the Atom window.

**Comment by meeshh** [comment]
i updated the package in atom, restarted and tested it but i still get the same result.

**Comment by icetee** [comment]
And add the new property to `.mailconfig`?

https://github.com/icetee/palladium/blame/c1fb29abab3f1932db49b6a19f363425c3fbf709/lib/settings/mailconfig.json

We are before publishing, we can only test it overwritten the file.

**Comment by meeshh** [comment]
i added the new property and it didn't work.

**Comment by icetee** [comment]
Can you give me more information, maybe example?

I try image src with external URL and set `disableImageEncode: true` and works.

I published the `v1.2.0` release.

**Comment by meeshh** [comment]
ok it works now. the update notification wasn't pushed to atom so i went to the packages tab and updated from there. 

thank you.
you can close this issue

**Comment by icetee** [comment]
If you have any ideas for developing a package, open a new issue.

Thanks
